// src/app/browser/components/lut-editor-dialog/solid-lut-editor-ramp-section.tsx
import { For, Show, type Accessor, type JSX } from 'solid-js';
import { MAX_RAMPS, type ColorRamp, type ColorRamp2dLutData } from '../../../../features/lut-editor/lut-editor-model.ts';
import { cx } from '../../styles/cx.ts';
import * as ui from '../../styles/ui-primitives.css.ts';
import { DropdownMenu } from '../solid-dropdown-menu.tsx';
import * as styles from './shared.css.ts';
import { formatPositionPercent, scheduleSelectAllTextIfFocused } from './shared.ts';

interface LutEditorRampSectionProps {
  tr: (key: string, values?: Record<string, string | number>) => string;
  rampData: Accessor<ColorRamp2dLutData | null>;
  selectedRamp: Accessor<ColorRamp | null>;
  selectedRampId: Accessor<string | null>;
  draggingRampListIdx: Accessor<number | null>;
  showDropBefore: (idx: number) => boolean;
  showDropAfterLast: () => boolean;
  canRemoveRamp: (rampId: string) => boolean;
  rampSwatchStyle: (ramp: ColorRamp) => string;
  rampRowElMap: Map<string, HTMLElement>;
  editingRampPositionId: Accessor<string | null>;
  rampPositionDraft: Accessor<string>;
  rampPositionInputRef: () => HTMLInputElement | undefined;
  setRampPositionInputRef: (input: HTMLInputElement | undefined) => void;
  onAddRamp: () => void;
  onSelectRamp: (rampId: string) => void;
  onRemoveRamp: (rampId: string) => void;
  onDuplicateSelectedRamp: () => void;
  onInvertSelectedRamp: () => void;
  onStartRampListDrag: (rampIdx: number, event: PointerEvent) => void;
  didRampListDragOccur: () => boolean;
  onBeginRampPositionEdit: (rampId: string, position: number) => void;
  onRampPositionInput: (rampId: string, value: string) => void;
  onCommitRampPositionDraft: (rampId: string) => void;
  onCancelRampPositionDraft: (position: number) => void;
  onRampPositionWheel: (rampId: string, currentPosition: number, event: WheelEvent) => void;
}

export function LutEditorRampSection(props: LutEditorRampSectionProps): JSX.Element {
  return (
    <div class={styles.rampSection}>
      <div class={styles.sectionHeader}>
        <div class={styles.sectionLabel}>{props.tr('lutEditor.rampListLabel')}</div>
        <div class={styles.sectionHeaderActions}>
          <button
            type="button"
            class={cx(ui.buttonBase, ui.secondaryButton)}
            onClick={props.onAddRamp}
            disabled={!props.rampData() || (props.rampData()?.ramps.length ?? 0) >= MAX_RAMPS}
          >
            {props.tr('lutEditor.addRamp')}
          </button>
          <Show when={props.selectedRamp()}>
            <DropdownMenu
              wrapperClass={ui.menuWrap}
              triggerClass={cx(ui.buttonBase, ui.menuTrigger)}
              menuClass={cx(ui.menu, styles.kebabMenu)}
              triggerAriaLabel={props.tr('lutEditor.rampMenuAria')}
              menuRole="menu"
            >
              {controls => (
                <>
                  <button
                    type="button"
                    class={ui.menuItem}
                    role="menuitem"
                    disabled={(props.rampData()?.ramps.length ?? 0) >= MAX_RAMPS}
                    onClick={() => { controls.closeMenu(); props.onDuplicateSelectedRamp(); }}
                  >
                    {props.tr('lutEditor.duplicateRamp')}
                  </button>
                  <button type="button" class={ui.menuItem} role="menuitem" onClick={() => { controls.closeMenu(); props.onInvertSelectedRamp(); }}>
                    {props.tr('lutEditor.invertRamp')}
                  </button>
                </>
              )}
            </DropdownMenu>
          </Show>
        </div>
      </div>
      <div class={styles.rampList}>
        <For each={props.rampData()?.ramps ?? []}>
          {(ramp, getIdx) => (
            <>
              <Show when={props.showDropBefore(getIdx())}>
                <div class={styles.rampDropIndicator} />
              </Show>
              <div
                class={cx(styles.rampRow, props.selectedRampId() === ramp.id && styles.rampRowSelected, props.draggingRampListIdx() === getIdx() && styles.rampRowDragging)}
                ref={element => { props.rampRowElMap.set(ramp.id, element); }}
                onPointerDown={event => props.onStartRampListDrag(getIdx(), event)}
                onClick={() => { if (!props.didRampListDragOccur()) props.onSelectRamp(ramp.id); }}
              >
                <div class={styles.rampSwatch} style={props.rampSwatchStyle(ramp)} />
                <span class={styles.rampY}>{props.tr('lutEditor.rampPosition')}: {formatPositionPercent(ramp.position)}%</span>
                <Show when={props.canRemoveRamp(ramp.id)}>
                  <button type="button" class={cx(ui.buttonBase, ui.ghostButton, ui.removeText)} onClick={event => { event.stopPropagation(); props.onRemoveRamp(ramp.id); }}>
                    {props.tr('lutEditor.removeRamp')}
                  </button>
                </Show>
              </div>
            </>
          )}
        </For>
        <Show when={props.showDropAfterLast()}>
          <div class={styles.rampDropIndicator} />
        </Show>
      </div>
      <Show when={props.selectedRamp()}>
        {getSelectedRamp => (
          <div class={styles.rampPositionEditor}>
            <label class={styles.stopEditorLabel}>{props.tr('lutEditor.rampPosition')}</label>
            <input
              ref={input => props.setRampPositionInputRef(input)}
              type="text"
              inputmode="decimal"
              class={styles.posInput}
              value={props.editingRampPositionId() === getSelectedRamp().id ? props.rampPositionDraft() : formatPositionPercent(getSelectedRamp().position)}
              onFocusIn={() => {
                props.onBeginRampPositionEdit(getSelectedRamp().id, getSelectedRamp().position);
                scheduleSelectAllTextIfFocused(props.rampPositionInputRef());
              }}
              onInput={event => props.onRampPositionInput(getSelectedRamp().id, (event.currentTarget as HTMLInputElement).value)}
              onBlur={() => props.onCommitRampPositionDraft(getSelectedRamp().id)}
              onKeyDown={event => {
                if (event.key === 'Enter') {
                  (event.currentTarget as HTMLInputElement).blur();
                } else if (event.key === 'Escape') {
                  props.onCancelRampPositionDraft(getSelectedRamp().position);
                  (event.currentTarget as HTMLInputElement).blur();
                }
              }}
              onWheel={event => props.onRampPositionWheel(getSelectedRamp().id, getSelectedRamp().position, event)}
            />
            <span class={styles.stopEditorUnit}>%</span>
          </div>
        )}
      </Show>
    </div>
  );
}

// src/app/browser/components/lut-editor-dialog/lut-editor-ramp-section.svelte
<script lang="ts">
  import type { ColorRamp } from '../../../../features/lut-editor/lut-editor-model.ts';
  import Button from '../svelte-button.svelte';
  import DropdownMenu from '../svelte-dropdown-menu.svelte';
  import { formatPositionPercent, scheduleSelectAllTextIfFocused } from './shared.ts';

  const {
    ramps = [],
    selectedRamp = null,
    selectedRampId = null,
    editingRampPositionId = null,
    rampPositionDraft = '',
    draggingRampListIdx = null,
    rampListLabel = '',
    addRampLabel = '',
    duplicateRampLabel = '',
    invertRampLabel = '',
    removeRampLabel = '',
    rampPositionLabel = '',
    rampMenuAriaLabel = '',
    maxRampsReached = false,
    canRemoveRamp = () => false,
    rampSwatchStyle = () => '',
    onAddRamp = () => undefined,
    onSelectRamp = () => undefined,
    onStartRampListDrag = () => undefined,
    onRemoveRamp = () => undefined,
    onDuplicateSelectedRamp = () => undefined,
    onInvertSelectedRamp = () => undefined,
    onBeginRampPositionEdit = () => undefined,
    onRampPositionInput = () => undefined,
    onCommitRampPosition = () => undefined,
    onCancelRampPositionEdit = () => undefined,
    onRampPositionWheel = () => undefined,
    shouldSuppressRampClick = () => false,
  }: {
    ramps?: readonly ColorRamp[];
    selectedRamp?: ColorRamp | null;
    selectedRampId?: string | null;
    editingRampPositionId?: string | null;
    rampPositionDraft?: string;
    draggingRampListIdx?: number | null;
    rampListLabel?: string;
    addRampLabel?: string;
    duplicateRampLabel?: string;
    invertRampLabel?: string;
    removeRampLabel?: string;
    rampPositionLabel?: string;
    rampMenuAriaLabel?: string;
    maxRampsReached?: boolean;
    canRemoveRamp?: (rampId: string) => boolean;
    rampSwatchStyle?: (ramp: ColorRamp) => string;
    onAddRamp?: () => void;
    onSelectRamp?: (rampId: string) => void;
    onStartRampListDrag?: (rampIndex: number, event: PointerEvent) => void;
    onRemoveRamp?: (rampId: string) => void;
    onDuplicateSelectedRamp?: () => void;
    onInvertSelectedRamp?: () => void;
    onBeginRampPositionEdit?: (rampId: string, currentDraft: string) => void;
    onRampPositionInput?: (rampId: string, nextDraft: string) => void;
    onCommitRampPosition?: (rampId: string) => void;
    onCancelRampPositionEdit?: (currentDraft: string) => void;
    onRampPositionWheel?: (rampId: string, currentPosition: number, event: WheelEvent) => void;
    shouldSuppressRampClick?: () => boolean;
  } = $props();

  let rampPositionInputRef = $state<HTMLInputElement | null>(null);

</script>

<div class="ramp-section">
  <div class="section-header">
    <div class="section-label">{rampListLabel}</div>
    <div class="section-header-actions">
      <Button variant="secondary" handlePress={onAddRamp} disabled={maxRampsReached}>
        {addRampLabel}
      </Button>
      {#if selectedRamp}
        <DropdownMenu
          wrapperClass="lut-editor-menu-wrap"
          menuClass="ui-menu lut-editor-menu-panel lut-editor-kebab-menu"
          triggerClassName="ui-menu-trigger"
          triggerVariant="menu-trigger"
          triggerAriaLabel={rampMenuAriaLabel}
          menuRole="menu"
          floating={true}
        >
          {#snippet trigger()}
            <span class="ui-symbol-kebab">...</span>
          {/snippet}
          {#snippet children(closeMenu)}
            <button
              type="button"
              class="ui-menu-item"
              role="menuitem"
              disabled={maxRampsReached}
              onclick={() => {
                closeMenu();
                onDuplicateSelectedRamp();
              }}
            >
              {duplicateRampLabel}
            </button>
            <button
              type="button"
              class="ui-menu-item"
              role="menuitem"
              onclick={() => {
                closeMenu();
                onInvertSelectedRamp();
              }}
            >
              {invertRampLabel}
            </button>
          {/snippet}
        </DropdownMenu>
      {/if}
    </div>
  </div>

  <div class="ramp-list">
    {#each ramps as ramp, index (ramp.id)}
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        data-ramp-id={ramp.id}
        class={`ramp-row ${selectedRampId === ramp.id ? 'ramp-row-selected' : ''} ${draggingRampListIdx === index ? 'ramp-row-dragging' : ''}`.trim()}
        onpointerdown={event => onStartRampListDrag(index, event)}
        onclick={() => {
          if (!shouldSuppressRampClick()) {
            onSelectRamp(ramp.id);
          }
        }}
      >
        <div class="ramp-swatch" style={rampSwatchStyle(ramp)}></div>
        <span class="ramp-position-text">{rampPositionLabel}: {formatPositionPercent(ramp.position)}%</span>
        {#if canRemoveRamp(ramp.id)}
          <Button variant={["destructive", "small"]} handlePress={() => onRemoveRamp(ramp.id)}>
            {removeRampLabel}
          </Button>
        {/if}
      </div>
    {/each}
  </div>

  {#if selectedRamp}
    <div class="position-editor">
      <label class="editor-label" for="lut-editor-ramp-position">{rampPositionLabel}</label>
      <input
        bind:this={rampPositionInputRef}
        id="lut-editor-ramp-position"
        type="text"
        inputmode="decimal"
        class="pos-input"
        value={editingRampPositionId === selectedRamp.id ? rampPositionDraft : formatPositionPercent(selectedRamp.position)}
        onfocus={() => {
          onBeginRampPositionEdit(selectedRamp.id, formatPositionPercent(selectedRamp.position));
          scheduleSelectAllTextIfFocused(rampPositionInputRef ?? undefined);
        }}
        oninput={event => onRampPositionInput(selectedRamp.id, (event.currentTarget as HTMLInputElement).value)}
        onblur={() => onCommitRampPosition(selectedRamp.id)}
        onkeydown={event => {
          if (event.key === 'Enter') {
            (event.currentTarget as HTMLInputElement).blur();
          } else if (event.key === 'Escape') {
            onCancelRampPositionEdit(formatPositionPercent(selectedRamp.position));
            (event.currentTarget as HTMLInputElement).blur();
          }
        }}
        onwheel={event => onRampPositionWheel(selectedRamp.id, selectedRamp.position, event)}
      />
      <span class="editor-unit">%</span>
    </div>
  {/if}
</div>

<style>
  .ramp-section {
    display: flex;
    flex-direction: column;
    flex: 0 0 auto;
    border-bottom: 1px solid var(--color-line);
    padding: 12px 16px;
    gap: 8px;
    max-height: 50%;
    overflow: auto;
  }

  .section-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
  }

  .section-header-actions {
    display: flex;
    align-items: stretch;
    gap: 8px;
    flex-shrink: 0;
  }

  .section-label {
    font-size: 11px;
    font-weight: 600;
    color: var(--color-muted);
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }

  .ramp-list {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .ramp-row {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 5px 8px;
    border-radius: 6px;
    cursor: pointer;
    border: 1px solid transparent;
    transition: background 0.1s, opacity 0.1s;
    user-select: none;
  }

  .ramp-row:hover {
    background: color-mix(in srgb, var(--color-text-strong), transparent 95%);
  }

  .ramp-row-selected {
    border-color: var(--color-accent);
    background: color-mix(in srgb, var(--color-accent), transparent 92%);
  }

  .ramp-row-dragging {
    opacity: 0.35;
    pointer-events: none;
  }

  :global(.ramp-row[data-drop-position="before"]) {
    box-shadow: inset 0 3px 0 var(--color-accent);
  }

  :global(.ramp-row[data-drop-position="after"]) {
    box-shadow: inset 0 -3px 0 var(--color-accent);
  }

  .ramp-swatch {
    width: 48px;
    height: 14px;
    border-radius: 3px;
    border: 1px solid color-mix(in srgb, var(--color-text-strong), transparent 90%);
    flex-shrink: 0;
  }

  .ramp-position-text {
    font-size: 11px;
    color: var(--color-text);
    font-variant-numeric: tabular-nums;
    flex: 1;
  }

  .position-editor {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 2px 2px;
  }

  .editor-label {
    font-size: 11px;
    color: var(--color-muted);
    min-width: 52px;
    flex-shrink: 0;
  }

  .editor-unit {
    font-size: 11px;
    color: var(--color-muted);
    font-variant-numeric: tabular-nums;
    min-width: 34px;
  }

  .pos-input {
    width: calc(6ch + 16px);
    box-sizing: content-box;
    font-size: 12px;
    padding: 3px 6px;
    border: 1px solid var(--color-control-border);
    border-radius: 4px;
    background: var(--color-surface-inset);
    color: var(--color-text);
    font-variant-numeric: tabular-nums;
    text-align: right;
  }
</style>
