// src/app/browser/components/panels/svelte-material-panel.svelte
<svelte:options customElement={{ tag: 'lut-material-panel', shadow: 'none' }} />

<script lang="ts">
  import { onDestroy } from 'svelte';
  import * as pipelineModel from '../../../../features/pipeline/pipeline-model.ts';
  import { getLanguage, subscribeLanguageChange, t } from '../../i18n.ts';
  import { MATERIAL_PRESETS, type MaterialPresetDefinition } from '../../ui/preview-presets.ts';
  import DropdownMenu from '../svelte-dropdown-menu.svelte';
  import { clamp, cloneMaterialSettings, getMaterialRangeStep, isValidMaterialSettings } from './shared.ts';

  type StatusKind = 'success' | 'error' | 'info';

  export let settings: pipelineModel.MaterialSettings = cloneMaterialSettings(pipelineModel.DEFAULT_MATERIAL_SETTINGS);
  export let commitSettings: (nextSettings: pipelineModel.MaterialSettings) => void = () => undefined;
  export let onStatus: (message: string, kind?: StatusKind) => void = () => undefined;

  let language = getLanguage();
  const disposeLanguageSync = subscribeLanguageChange(nextLanguage => {
    language = nextLanguage;
  });

  onDestroy(() => {
    disposeLanguageSync();
  });

  function tr(key: Parameters<typeof t>[0], values?: Record<string, string | number>): string {
    language;
    return values ? t(key, values as never) : t(key);
  }

  function handleBaseColorInput(event: Event): void {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      onStatus(tr('panel.baseColorInputMissing'), 'error');
      return;
    }

    const parsed = pipelineModel.parseHexColor(input.value);
    if (!parsed) {
      onStatus(tr('panel.baseColorInvalid'), 'error');
      return;
    }

    commitSettings({
      ...settings,
      baseColor: [parsed[0], parsed[1], parsed[2]],
    });
  }

  function handleRangeInput(event: Event, binding: pipelineModel.MaterialRangeBinding): void {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      onStatus(tr('panel.rangeInputMissing', { label: binding.label }), 'error');
      return;
    }

    const parsed = Number(input.value);
    if (!Number.isFinite(parsed)) {
      onStatus(tr('panel.rangeInvalid', { label: binding.label }), 'error');
      return;
    }

    const next = cloneMaterialSettings(settings);
    next[binding.key] = clamp(parsed, binding.min, binding.max);
    commitSettings(next);
  }

  function handleMaterialRangeWheel(event: WheelEvent, binding: pipelineModel.MaterialRangeBinding): void {
    event.preventDefault();
    const step = Number(getMaterialRangeStep(binding.key));
    const next = cloneMaterialSettings(settings);
    const delta = event.deltaY < 0 ? step : -step;
    next[binding.key] = clamp(settings[binding.key] + delta, binding.min, binding.max);
    commitSettings(next);
  }

  function applyMaterialPreset(preset: MaterialPresetDefinition): boolean {
    if (!isValidMaterialSettings(preset.settings)) {
      onStatus(tr('panel.status.materialPresetInvalidValue', { value: preset.key }), 'error');
      return false;
    }

    commitSettings(cloneMaterialSettings(preset.settings));
    onStatus(tr('panel.status.materialPresetApplied', { name: tr(preset.labelKey) }), 'info');
    return true;
  }

  $: baseColorHex = pipelineModel.colorToHex(settings.baseColor);
</script>

<div class="panel-root">
  <div class="panel-head">
    <div>
      <div class="section-label">Material</div>
      <div class="help-text">{tr('panel.materialHelp')}</div>
    </div>
    <DropdownMenu
      wrapperClass="ui-menu-wrap"
      triggerClassName="ui-menu-trigger"
      menuClass="ui-menu"
      triggerAriaLabel={tr('panel.materialPreset')}
      menuRole="menu"
      triggerVariant="menu-trigger"
    >
      <span slot="trigger" class="ui-symbol-kebab">...</span>
      <svelte:fragment let:closeMenu>
        <div class="ui-menu-header">{tr('panel.materialPreset')}</div>
        {#each MATERIAL_PRESETS as preset}
          <button
            type="button"
            class="ui-menu-item"
            role="menuitem"
            on:click={() => {
              if (applyMaterialPreset(preset)) {
                closeMenu();
              }
            }}
          >
            {tr(preset.labelKey)}
          </button>
        {/each}
      </svelte:fragment>
    </DropdownMenu>
  </div>

  <div class="grid">
    <label class="field color-field">
      <span class="label-row">
        <span class="label-text">Base Color</span>
        <span class="value-text" id="mat-base-color-value">{baseColorHex}</span>
      </span>
      <input class="color-input" type="color" id="mat-base-color" value={baseColorHex} on:input={handleBaseColorInput} />
    </label>

    {#each pipelineModel.MATERIAL_RANGE_BINDINGS as binding}
      <label class="field">
        <span class="label-row">
          <span class="label-text">{binding.label}</span>
          <span class="value-text" id={binding.outputId}>{settings[binding.key].toFixed(binding.fractionDigits)}</span>
        </span>
        <input
          class="range-input"
          type="range"
          id={binding.inputId}
          min={String(binding.min)}
          max={String(binding.max)}
          step={getMaterialRangeStep(binding.key)}
          value={String(settings[binding.key])}
          on:input={event => handleRangeInput(event, binding)}
          on:change={event => handleRangeInput(event, binding)}
          on:wheel={event => handleMaterialRangeWheel(event, binding)}
        />
      </label>
    {/each}
  </div>
</div>

<style>
  .panel-root {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .panel-head {
    display: flex;
    justify-content: space-between;
    gap: 8px;
  }

  .help-text {
    font-size: 11px;
    color: var(--color-muted);
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 8px;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 9px 10px;
    border: 1px solid var(--color-panel-border-strong, #464646);
    border-radius: 12px;
    background: color-mix(in srgb, var(--color-panel), var(--color-bg) 4%);
  }

  .color-field {
    grid-column: span 2;
  }

  .label-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
  }

  .label-text {
    font-size: 11px;
    font-weight: 700;
    color: var(--color-text-strong);
  }

  .value-text {
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    color: var(--color-muted);
  }

  .color-input {
    width: 100%;
    height: 34px;
    border: 1px solid var(--color-control-border, var(--color-line));
    border-radius: 9px;
    background: var(--color-control-bg, var(--color-panel));
    padding: 4px;
  }

  .range-input {
    width: 100%;
    accent-color: var(--color-accent);
  }

  @media (max-width: 1180px) {
    .grid {
      grid-template-columns: 1fr;
    }

    .color-field {
      grid-column: span 1;
    }
  }

  @media (max-width: 900px) {
    .panel-head {
      flex-direction: column;
      align-items: flex-start;
    }
  }
</style>

// src/app/browser/components/panels/solid-material-panel.tsx
import { For, type JSX } from 'solid-js';
import * as pipelineModel from '../../../../features/pipeline/pipeline-model.ts';
import { t, useLanguage } from '../../i18n.ts';
import { cx } from '../../styles/cx.ts';
import * as ui from '../../styles/ui-primitives.css.ts';
import { MATERIAL_PRESETS, type MaterialPresetDefinition } from '../../ui/preview-presets.ts';
import { DropdownMenu } from '../solid-dropdown-menu.tsx';
import * as styles from './shared.css.ts';
import type { MaterialPanelProps } from './shared.ts';
import { clamp, cloneMaterialSettings, getMaterialRangeStep, isValidMaterialSettings } from './shared.ts';

export function MaterialPanel(props: MaterialPanelProps): JSX.Element {
  const language = useLanguage();

  const tr = (key: string, values?: Record<string, string | number>): string => {
    language();
    return t(key, values);
  };

  const handleBaseColorInput = (event: Event): void => {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      props.onStatus(tr('panel.baseColorInputMissing'), 'error');
      return;
    }
    const parsed = pipelineModel.parseHexColor(input.value);
    if (!parsed) {
      props.onStatus(tr('panel.baseColorInvalid'), 'error');
      return;
    }
    const current = props.settings();
    props.commitSettings({ ...current, baseColor: [parsed[0], parsed[1], parsed[2]] });
  };

  const handleRangeInput = (event: Event, binding: pipelineModel.MaterialRangeBinding): void => {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      props.onStatus(tr('panel.rangeInputMissing', { label: binding.label }), 'error');
      return;
    }
    const parsed = Number(input.value);
    if (!Number.isFinite(parsed)) {
      props.onStatus(tr('panel.rangeInvalid', { label: binding.label }), 'error');
      return;
    }
    const current = props.settings();
    const next = cloneMaterialSettings(current);
    next[binding.key] = clamp(parsed, binding.min, binding.max);
    props.commitSettings(next);
  };

  const handleMaterialRangeWheel = (event: WheelEvent, binding: pipelineModel.MaterialRangeBinding): void => {
    event.preventDefault();
    const step = Number(getMaterialRangeStep(binding.key));
    const delta = event.deltaY < 0 ? step : -step;
    const current = props.settings();
    const next = cloneMaterialSettings(current);
    next[binding.key] = clamp(current[binding.key] + delta, binding.min, binding.max);
    props.commitSettings(next);
  };

  const applyMaterialPreset = (preset: MaterialPresetDefinition): boolean => {
    if (!isValidMaterialSettings(preset.settings)) {
      props.onStatus(tr('panel.status.materialPresetInvalidValue', { value: preset.key }), 'error');
      return false;
    }
    props.commitSettings(cloneMaterialSettings(preset.settings));
    props.onStatus(tr('panel.status.materialPresetApplied', { name: tr(preset.labelKey) }), 'info');
    return true;
  };

  return (
    <div class={styles.panelRoot}>
      <div class={styles.panelHead}>
        <div>
          <div class={ui.sectionLabel}>Material</div>
          <div class={styles.helpText}>{tr('panel.materialHelp')}</div>
        </div>
        <DropdownMenu
          wrapperClass={ui.menuWrap}
          triggerClass={cx(ui.buttonBase, ui.menuTrigger)}
          menuClass={ui.menu}
          triggerAriaLabel={tr('panel.materialPreset')}
          menuRole="menu"
        >
          {controls => (
            <>
              <div class={ui.menuHeader}>{tr('panel.materialPreset')}</div>
              <For each={MATERIAL_PRESETS}>
                {preset => (
                  <button
                    type="button"
                    class={ui.menuItem}
                    role="menuitem"
                    onClick={() => {
                      if (applyMaterialPreset(preset)) controls.closeMenu();
                    }}
                  >
                    {tr(preset.labelKey)}
                  </button>
                )}
              </For>
            </>
          )}
        </DropdownMenu>
      </div>

      <div class={styles.grid}>
        <label class={cx(styles.field, styles.colorField)}>
          <span class={styles.labelRow}>
            <span class={styles.labelText}>Base Color</span>
            <span class={styles.valueText} id="mat-base-color-value">{pipelineModel.colorToHex(props.settings().baseColor)}</span>
          </span>
          <input class={ui.colorInput} type="color" id="mat-base-color" value={pipelineModel.colorToHex(props.settings().baseColor)} onInput={handleBaseColorInput} />
        </label>

        <For each={pipelineModel.MATERIAL_RANGE_BINDINGS}>
          {binding => (
            <label class={styles.field}>
              <span class={styles.labelRow}>
                <span class={styles.labelText}>{binding.label}</span>
                <span class={styles.valueText} id={binding.outputId}>{props.settings()[binding.key].toFixed(binding.fractionDigits)}</span>
              </span>
              <input
                class={ui.rangeInput}
                type="range"
                id={binding.inputId}
                min={String(binding.min)}
                max={String(binding.max)}
                step={getMaterialRangeStep(binding.key)}
                value={String(props.settings()[binding.key])}
                onInput={event => handleRangeInput(event, binding)}
                onChange={event => handleRangeInput(event, binding)}
                onWheel={event => handleMaterialRangeWheel(event, binding)}
              />
            </label>
          )}
        </For>
      </div>
    </div>
  );
}
