// src/app/browser/components/panels/svelte-light-panel.svelte
<svelte:options customElement={{ tag: 'lut-light-panel', shadow: 'none' }} />

<script lang="ts">
  import { onDestroy } from 'svelte';
  import * as pipelineModel from '../../../../features/pipeline/pipeline-model.ts';
  import { getLanguage, subscribeLanguageChange, t } from '../../i18n.ts';
  import { LIGHT_PRESETS, type LightPresetDefinition } from '../../ui/preview-presets.ts';
  import DropdownMenu from '../svelte-dropdown-menu.svelte';
  import { clamp, cloneLightSettings, getLightRangeStep, isLightAngleBinding, isValidLightSettings } from './shared.ts';

  type StatusKind = 'success' | 'error' | 'info';

  export let settings: pipelineModel.LightSettings = cloneLightSettings(pipelineModel.DEFAULT_LIGHT_SETTINGS);
  export let commitSettings: (nextSettings: pipelineModel.LightSettings) => void = () => undefined;
  export let onStatus: (message: string, kind?: StatusKind) => void = () => undefined;

  let language = getLanguage();
  const disposeLanguageSync = subscribeLanguageChange(nextLanguage => {
    language = nextLanguage;
  });

  onDestroy(() => {
    disposeLanguageSync();
  });

  function tr(key: Parameters<typeof t>[0], values?: Record<string, string | number>): string {
    language;
    return values ? t(key, values as never) : t(key);
  }

  function handleColorInput(event: Event, kind: 'light' | 'ambient'): void {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      onStatus(tr(kind === 'light' ? 'panel.lightColorInputMissing' : 'panel.ambientColorInputMissing'), 'error');
      return;
    }

    const parsed = pipelineModel.parseHexColor(input.value);
    if (!parsed) {
      onStatus(tr(kind === 'light' ? 'panel.lightColorInvalid' : 'panel.ambientColorInvalid'), 'error');
      return;
    }

    commitSettings({
      ...settings,
      ...(kind === 'light'
        ? { lightColor: [parsed[0], parsed[1], parsed[2]] as [number, number, number] }
        : { ambientColor: [parsed[0], parsed[1], parsed[2]] as [number, number, number] }),
    });
  }

  function handleRangeInput(event: Event, binding: pipelineModel.LightRangeBinding): void {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      onStatus(tr('panel.rangeInputMissing', { label: binding.label }), 'error');
      return;
    }

    const parsed = Number(input.value);
    if (!Number.isFinite(parsed)) {
      onStatus(tr('panel.rangeInvalid', { label: binding.label }), 'error');
      return;
    }

    const next = cloneLightSettings(settings);
    next[binding.key] = clamp(parsed, binding.min, binding.max);
    commitSettings(next);
  }

  function handleLightRangeWheel(event: WheelEvent, binding: pipelineModel.LightRangeBinding): void {
    event.preventDefault();
    const step = Number(getLightRangeStep(binding));
    const delta = event.deltaY < 0 ? step : -step;
    const next = cloneLightSettings(settings);
    next[binding.key] = clamp(settings[binding.key] + delta, binding.min, binding.max);
    commitSettings(next);
  }

  function toggleGizmo(): void {
    commitSettings({ ...settings, showGizmo: !settings.showGizmo });
  }

  function applyLightPreset(preset: LightPresetDefinition): boolean {
    if (!isValidLightSettings(preset.settings)) {
      onStatus(tr('panel.status.lightPresetInvalidValue', { value: preset.key }), 'error');
      return false;
    }

    commitSettings(cloneLightSettings(preset.settings));
    onStatus(tr('panel.status.lightPresetApplied', { name: tr(preset.labelKey) }), 'info');
    return true;
  }

  $: lightColorHex = pipelineModel.colorToHex(settings.lightColor);
  $: ambientColorHex = pipelineModel.colorToHex(settings.ambientColor);
</script>

<div class="panel-root">
  <div class="panel-head">
    <div>
      <div class="section-label">Light</div>
      <div class="help-text">{tr('panel.lightHelp')}</div>
    </div>
    <div class="light-actions">
      <button
        type="button"
        class="guide-button"
        id="btn-toggle-light-gizmo"
        aria-pressed={settings.showGizmo ? 'true' : 'false'}
        on:click={toggleGizmo}
      >
        {tr('panel.guide')}
      </button>

      <DropdownMenu
        wrapperClass="ui-menu-wrap"
        triggerClassName="ui-menu-trigger"
        menuClass="ui-menu"
        triggerAriaLabel={tr('panel.lightPreset')}
        menuRole="menu"
        triggerVariant="menu-trigger"
      >
        <span slot="trigger" class="ui-symbol-kebab">...</span>
        <svelte:fragment let:closeMenu>
          <div class="ui-menu-header">{tr('panel.lightPreset')}</div>
          {#each LIGHT_PRESETS as preset}
            <button
              type="button"
              class="ui-menu-item"
              role="menuitem"
              on:click={() => {
                if (applyLightPreset(preset)) {
                  closeMenu();
                }
              }}
            >
              {tr(preset.labelKey)}
            </button>
          {/each}
        </svelte:fragment>
      </DropdownMenu>
    </div>
  </div>

  <div class="grid">
    <label class="field color-field">
      <span class="label-row">
        <span class="label-text">Light Color</span>
        <span class="value-text" id="light-color-value">{lightColorHex}</span>
      </span>
      <input class="color-input" type="color" id="light-color" value={lightColorHex} on:input={event => handleColorInput(event, 'light')} />
    </label>

    <label class="field color-field">
      <span class="label-row">
        <span class="label-text">Ambient Color</span>
        <span class="value-text" id="light-ambient-color-value">{ambientColorHex}</span>
      </span>
      <input class="color-input" type="color" id="light-ambient-color" value={ambientColorHex} on:input={event => handleColorInput(event, 'ambient')} />
    </label>

    {#each pipelineModel.LIGHT_RANGE_BINDINGS as binding}
      <label class="field">
        <span class="label-row">
          <span class="label-text">{binding.label}</span>
          <span class="value-text" id={binding.outputId}>
            {#if isLightAngleBinding(binding)}
              {settings[binding.key].toFixed(binding.fractionDigits)}°
            {:else}
              {settings[binding.key].toFixed(binding.fractionDigits)}
            {/if}
          </span>
        </span>
        <input
          class="range-input"
          type="range"
          id={binding.inputId}
          min={String(binding.min)}
          max={String(binding.max)}
          step={getLightRangeStep(binding)}
          value={String(settings[binding.key])}
          on:input={event => handleRangeInput(event, binding)}
          on:change={event => handleRangeInput(event, binding)}
          on:wheel={event => handleLightRangeWheel(event, binding)}
        />
      </label>
    {/each}
  </div>
</div>

<style>
  .panel-root {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .panel-head {
    display: flex;
    justify-content: space-between;
    gap: 8px;
  }

  .help-text {
    font-size: 11px;
    color: var(--color-muted);
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 8px;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 9px 10px;
    border: 1px solid var(--color-panel-border-strong, #464646);
    border-radius: 12px;
    background: color-mix(in srgb, var(--color-panel), var(--color-bg) 4%);
  }

  .color-field {
    grid-column: span 2;
  }

  .label-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
  }

  .label-text {
    font-size: 11px;
    font-weight: 700;
    color: var(--color-text-strong);
  }

  .value-text {
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    color: var(--color-muted);
  }

  .light-actions {
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }

  .light-actions > * {
    flex-shrink: 0;
  }

  .guide-button {
    border: 1px solid var(--color-line);
    background: var(--color-panel);
    border-radius: 8px;
    padding: 6px 11px;
    font-size: 12px;
    color: var(--color-muted);
    cursor: pointer;
    transition: 120ms ease;
  }

  .guide-button:hover {
    border-color: var(--color-accent);
    transform: translateY(-1px);
  }

  .guide-button[aria-pressed="true"] {
    border-color: var(--color-accent);
    color: color-mix(in srgb, var(--color-text-strong), var(--color-accent) 24%);
  }

  .color-input {
    width: 100%;
    height: 34px;
    border: 1px solid var(--color-control-border, var(--color-line));
    border-radius: 9px;
    background: var(--color-control-bg, var(--color-panel));
    padding: 4px;
  }

  .range-input {
    width: 100%;
    accent-color: var(--color-accent);
  }

  @media (max-width: 1180px) {
    .grid {
      grid-template-columns: 1fr;
    }

    .color-field {
      grid-column: span 1;
    }
  }

  @media (max-width: 900px) {
    .panel-head {
      flex-direction: column;
      align-items: flex-start;
    }

    .light-actions {
      width: 100%;
      justify-content: space-between;
    }
  }
</style>

// src/app/browser/components/panels/solid-light-panel.tsx
import { For, type JSX } from 'solid-js';
import * as pipelineModel from '../../../../features/pipeline/pipeline-model.ts';
import { t, useLanguage } from '../../i18n.ts';
import { cx } from '../../styles/cx.ts';
import * as ui from '../../styles/ui-primitives.css.ts';
import { LIGHT_PRESETS, type LightPresetDefinition } from '../../ui/preview-presets.ts';
import { DropdownMenu } from '../solid-dropdown-menu.tsx';
import * as styles from './shared.css.ts';
import type { LightPanelProps } from './shared.ts';
import { clamp, cloneLightSettings, getLightRangeStep, isLightAngleBinding, isValidLightSettings } from './shared.ts';

export function LightPanel(props: LightPanelProps): JSX.Element {
  const language = useLanguage();

  const tr = (key: string, values?: Record<string, string | number>): string => {
    language();
    return t(key, values);
  };

  const handleLightColorInput = (event: Event): void => {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      props.onStatus(tr('panel.lightColorInputMissing'), 'error');
      return;
    }
    const parsed = pipelineModel.parseHexColor(input.value);
    if (!parsed) {
      props.onStatus(tr('panel.lightColorInvalid'), 'error');
      return;
    }
    const current = props.settings();
    props.commitSettings({ ...current, lightColor: [parsed[0], parsed[1], parsed[2]] });
  };

  const handleAmbientColorInput = (event: Event): void => {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      props.onStatus(tr('panel.ambientColorInputMissing'), 'error');
      return;
    }
    const parsed = pipelineModel.parseHexColor(input.value);
    if (!parsed) {
      props.onStatus(tr('panel.ambientColorInvalid'), 'error');
      return;
    }
    const current = props.settings();
    props.commitSettings({ ...current, ambientColor: [parsed[0], parsed[1], parsed[2]] });
  };

  const handleRangeInput = (event: Event, binding: pipelineModel.LightRangeBinding): void => {
    const input = event.currentTarget as HTMLInputElement | null;
    if (!input) {
      props.onStatus(tr('panel.rangeInputMissing', { label: binding.label }), 'error');
      return;
    }
    const parsed = Number(input.value);
    if (!Number.isFinite(parsed)) {
      props.onStatus(tr('panel.rangeInvalid', { label: binding.label }), 'error');
      return;
    }
    const current = props.settings();
    const next = cloneLightSettings(current);
    next[binding.key] = clamp(parsed, binding.min, binding.max);
    props.commitSettings(next);
  };

  const handleLightRangeWheel = (event: WheelEvent, binding: pipelineModel.LightRangeBinding): void => {
    event.preventDefault();
    const step = Number(getLightRangeStep(binding));
    const delta = event.deltaY < 0 ? step : -step;
    const current = props.settings();
    const next = cloneLightSettings(current);
    next[binding.key] = clamp(current[binding.key] + delta, binding.min, binding.max);
    props.commitSettings(next);
  };

  const toggleGizmo = (): void => {
    const current = props.settings();
    props.commitSettings({ ...current, showGizmo: !current.showGizmo });
  };

  const applyLightPreset = (preset: LightPresetDefinition): boolean => {
    if (!isValidLightSettings(preset.settings)) {
      props.onStatus(tr('panel.status.lightPresetInvalidValue', { value: preset.key }), 'error');
      return false;
    }
    props.commitSettings(cloneLightSettings(preset.settings));
    props.onStatus(tr('panel.status.lightPresetApplied', { name: tr(preset.labelKey) }), 'info');
    return true;
  };

  return (
    <div class={styles.panelRoot}>
      <div class={styles.panelHead}>
        <div>
          <div class={ui.sectionLabel}>Light</div>
          <div class={styles.helpText}>{tr('panel.lightHelp')}</div>
        </div>
        <div class={styles.lightActions}>
          <button
            type="button"
            class={cx(ui.buttonBase, ui.secondaryButton, styles.lightToggleButton)}
            id="btn-toggle-light-gizmo"
            aria-pressed={props.settings().showGizmo ? 'true' : 'false'}
            onClick={toggleGizmo}
          >
            {tr('panel.guide')}
          </button>

          <DropdownMenu
            wrapperClass={ui.menuWrap}
            triggerClass={cx(ui.buttonBase, ui.menuTrigger)}
            menuClass={ui.menu}
            triggerAriaLabel={tr('panel.lightPreset')}
            menuRole="menu"
          >
            {controls => (
              <>
                <div class={ui.menuHeader}>{tr('panel.lightPreset')}</div>
                <For each={LIGHT_PRESETS}>
                  {preset => (
                    <button
                      type="button"
                      class={ui.menuItem}
                      role="menuitem"
                      onClick={() => {
                        if (applyLightPreset(preset)) controls.closeMenu();
                      }}
                    >
                      {tr(preset.labelKey)}
                    </button>
                  )}
                </For>
              </>
            )}
          </DropdownMenu>
        </div>
      </div>

      <div class={styles.grid}>
        <label class={cx(styles.field, styles.colorField)}>
          <span class={styles.labelRow}>
            <span class={styles.labelText}>Light Color</span>
            <span class={styles.valueText} id="light-color-value">{pipelineModel.colorToHex(props.settings().lightColor)}</span>
          </span>
          <input class={ui.colorInput} type="color" id="light-color" value={pipelineModel.colorToHex(props.settings().lightColor)} onInput={handleLightColorInput} />
        </label>

        <label class={cx(styles.field, styles.colorField)}>
          <span class={styles.labelRow}>
            <span class={styles.labelText}>Ambient Color</span>
            <span class={styles.valueText} id="light-ambient-color-value">{pipelineModel.colorToHex(props.settings().ambientColor)}</span>
          </span>
          <input class={ui.colorInput} type="color" id="light-ambient-color" value={pipelineModel.colorToHex(props.settings().ambientColor)} onInput={handleAmbientColorInput} />
        </label>

        <For each={pipelineModel.LIGHT_RANGE_BINDINGS}>
          {binding => (
            <label class={styles.field}>
              <span class={styles.labelRow}>
                <span class={styles.labelText}>{binding.label}</span>
                <span class={styles.valueText} id={binding.outputId}>
                  {isLightAngleBinding(binding)
                    ? `${props.settings()[binding.key].toFixed(binding.fractionDigits)}°`
                    : props.settings()[binding.key].toFixed(binding.fractionDigits)}
                </span>
              </span>
              <input
                class={ui.rangeInput}
                type="range"
                id={binding.inputId}
                min={String(binding.min)}
                max={String(binding.max)}
                step={getLightRangeStep(binding)}
                value={String(props.settings()[binding.key])}
                onInput={event => handleRangeInput(event, binding)}
                onChange={event => handleRangeInput(event, binding)}
                onWheel={event => handleLightRangeWheel(event, binding)}
              />
            </label>
          )}
        </For>
      </div>
    </div>
  );
}
